import os


import random

print("           ----A simple Hacker name generator----            ")

lower_case = "abcdefghijklmdfhsdhcnGZAwQUqrstuvwxyz"
upper_case = "ABCDEFGHIJKLMNOhYFJRSTUVWXYZ"
number = "01346"


Use_for = lower_case + upper_case + number
length_for_name = 5

name = "".join(random.sample(Use_for, length_for_name))
pc_username = os.getenv("UserName")

with open('hackernames.txt', "w", encoding="utf-8") as f:
    f.write(f"@{pc_username}\n")
    f.write(f"Hacker names\n\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    name = "".join(random.sample(Use_for, length_for_name))
    f.write(f"name: {name}\n")
    #it is done

os.system("start hackernames.txt")


